=== Asier-R/ingsoft2020/DATOS_ESTRUCTURA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Pais">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="E" type="xs:float" minOccurs="1"/>
				<xs:element name="P" type="xs:float" minOccurs="1"/>
				<xs:element name="V" type="xs:float" minOccurs="1"/>
				<xs:element name="maxDias" type="xs:integer" minOccurs="1"/>
				<xs:element name="Comunidades">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Comunidad" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nombre" type="xs:string"/>
										<xs:element name="poblacion" type="xs:integer"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Asier-R/ingsoft2020/DATOS_ENTRADA.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pais  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="DATOS_ESTRUCTURA.xsd">
	<E>0.5</E>
	<P>2</P>
	<V>5</V>
	<maxDias>2</maxDias>
	<Comunidades>
		<Comunidad>
			<nombre>Andalucia</nombre>
			<poblacion>1000</poblacion>
		</Comunidad>
		<Comunidad>
			<nombre>Madrid</nombre>
			<poblacion>2000</poblacion>
		</Comunidad>
	</Comunidades>
</Pais>
